version: '2'
services:
  # TODO: add other services db, redis, sidekiq, etc
  # db:
    # image: postgres
  web:
    build: .
    restart: always
    volumes:
      - .:/oregondigital_2
    ports:
      - "3000:3000"
    # command: bundle exec rake db:migrate && bundle exec rake jetty:clean && bundle exec rake jetty:config && bundle exec rake jetty:start && bundle exec rails s -p 3000 -b '0.0.0.0'

    command: ./docker-start-app.sh
    # depends_on:
      # - db
