RDF_VOCABS = {
  :dcmitype             =>  { :uri => 'http://purl.org/dc/dcmitype/', :source => 'http://dublincore.org/2012/06/14/dctype.rdf' },
  :marcrel              =>  { :uri => 'http://id.loc.gov/vocabulary/relators/', :source => 'http://id.loc.gov/vocabulary/relators.nt' },
  :dwc                  =>  { :uri => 'http://rs.tdwg.org/dwc/terms', :strict => false },
  :iso_639_1            =>  { :uri => 'http://id.loc.gov/vocabulary/iso639-1/', :source => 'http://id.loc.gov/vocabulary/iso639-1.nt'},
  :iso_639_2            =>  { :uri => 'http://id.loc.gov/vocabulary/iso639-2/', :source => 'http://id.loc.gov/vocabulary/iso639-2.nt'},
  :marc_lang            =>  { :uri => 'http://id.loc.gov/vocabulary/languages/', :source => 'http://id.loc.gov/vocabulary/languages.nt'},
  :premis               =>  { :uri => 'http://www.loc.gov/premis/rdf/v1#', :source => 'http://www.loc.gov/premis/rdf/v1.nt' },
  :geonames             =>  { :uri => 'http://sws.geonames.org/', :strict => false, :fetch => false },
  :lcsh                 =>  { :uri => 'http://id.loc.gov/authorities/subjects', :strict => false, :fetch => false },
  :lcnames              =>  { :uri => 'http://id.loc.gov/authorities/names', :strict => false, :fetch => false },
  :tgm                  =>  { :uri => 'http://id.loc.gov/vocabulary/graphicMaterials', :strict => false, :fetch => false },
  :afs_ethn             =>  { :uri => 'http://id.loc.gov/vocabulary/ethnographicTerms', :strict => false, :fetch => false },
  :lc_orgs              =>  { :uri => 'http://id.loc.gov/vocabulary/organizations', :strict => false, :fetch => false },
  :aat                  =>  { :uri => 'http://vocab.getty.edu/aat/', :strict => false, :fetch => false },
  :getty_tgn            =>  { :uri => 'http://vocab.getty.edu/tgn/', :strict => false, :fetch => false },
  :cclicenses           =>  { :uri => 'http://creativecommons.org/licenses/', :source => 'https://raw.github.com/OregonDigital/opaque_ns/master/cclicenses/cclicenses.nt'},
  :ccpublic             =>  { :uri => 'http://creativecommons.org/publicdomain/', :source => 'https://raw.github.com/OregonDigital/opaque_ns/master/cclicenses/cclicenses.nt'},
  :uonames              =>  { :uri => 'http://opaquenamespace.org/ns/uo-names/', :source => 'https://raw.github.com/OregonDigital/opaque_ns/master/uo/names.jsonld', :strict => false, :fetch => false },
  :rights               =>  { :uri => 'http://opaquenamespace.org/rights/', :source => 'https://raw.github.com/OregonDigital/opaque_ns/master/rights.jsonld', :strict => true },
  :eurights             =>  { :uri => 'http://www.europeana.eu/rights/', :source => 'https://raw.github.com/OregonDigital/opaque_ns/master/eurights/rightsstatements.nt', :strict => true },
  :mimetype             =>  { :uri => 'http://purl.org/NET/mediatypes/', :source => 'http://mediatypes.appspot.com/dump.rdf' },
  :opaquenamespace      =>  { :uri => 'http://opaquenamespace.org/ns/', :source => 'https://raw.github.com/OregonDigital/opaque_ns/master/opaquenamespace.jsonld', :strict => false, :fetch => false },
  :oregon_universities  =>  { :uri => 'http://dbpedia.org/resource/', :source => 'https://raw.github.com/OregonDigital/opaque_ns/master/oregon_universities.jsonld', :strict => false, :fetch => false },
  :set                  =>  { :uri => 'http://oregondigital.org/resource/', :strict => false, :fetch => false },
  :holding              =>  { :uri => 'http://purl.org/ontology/holding#' },
  :creator              =>  { :uri => 'http://opaquenamespace.org/ns/creator/', :source => 'https://raw.github.com/OregonDigital/opaque_ns/master/creator.jsonld', :strict => false, :fetch => false },
  :culture              =>  { :uri => 'http://opaquenamespace.org/ns/culture/', :source => 'https://raw.github.com/OregonDigital/opaque_ns/master/culture.jsonld', :strict => false, :fetch => false },
  :localcoll            =>  { :uri => 'http://opaquenamespace.org/ns/localCollectionName/', :source => 'https://raw.github.com/OregonDigital/opaque_ns/master/localCollectionName.jsonld', :strict => false, :fetch => false },
  :institutions         =>  { :uri => 'http://opaquenamespace.org/resource/', :source => 'https://raw.github.com/OregonDigital/opaque_ns/master/oregondigital_orgs.jsonld', :strict => false, :fetch => false },
  :people               =>  { :uri => 'http://opaquenamespace.org/ns/people/', :source => 'https://raw.github.com/OregonDigital/opaque_ns/master/people.jsonld', :strict => false, :fetch => false },
  :repository           =>  { :uri => 'http://opaquenamespace.org/ns/repository/', :source => 'https://raw.github.com/OregonDigital/opaque_ns/master/repository.jsonld', :strict => false, :fetch => false },
  :sciclass             =>  { :uri => 'http://opaquenamespace.org/ns/class/', :source => 'https://raw.github.com/OregonDigital/opaque_ns/master/scientific_class.jsonld', :strict => false, :fetch => false },
  :scicommon            =>  { :uri => 'http://opaquenamespace.org/ns/commonNames/', :source => 'https://raw.github.com/OregonDigital/opaque_ns/master/scientific_commonNames.jsonld', :strict => false, :fetch => false },
  :scigenus             =>  { :uri => 'http://opaquenamespace.org/ns/genus/', :source => 'https://raw.github.com/OregonDigital/opaque_ns/master/scientific_genus.jsonld', :strict => false, :fetch => false },
  :sciphylum            =>  { :uri => 'http://opaquenamespace.org/ns/phylum/', :source => 'https://raw.githubusercontent.com/OregonDigital/opaque_ns/master/scientific_phylum.jsonld', :strict => false, :fetch => false },
  :styleperiod          =>  { :uri => 'http://opaquenamespace.org/ns/stylePeriod/', :source => 'https://raw.github.com/OregonDigital/opaque_ns/master/stylePeriod.jsonld', :strict => false, :fetch => false },
  :subject              =>  { :uri => 'http://opaquenamespace.org/ns/subject/', :source => 'https://raw.github.com/OregonDigital/opaque_ns/master/subject.jsonld', :strict => false, :fetch => false },
  :technique            =>  { :uri => 'http://opaquenamespace.org/ns/technique/', :source => 'https://raw.github.com/OregonDigital/opaque_ns/master/technique.jsonld', :strict => false, :fetch => false },
  :worktype             =>  { :uri => 'http://opaquenamespace.org/ns/workType/', :source => 'https://raw.github.com/OregonDigital/opaque_ns/master/workType.jsonld', :strict => false, :fetch => false },
  :ubio                 =>  { :uri => 'http://identifiers.org/ubio.namebank/', :strict => false, :fetch => false },
  :itis                 =>  { :uri => 'http://www.itis.gov/ITISWebService/', :strict => false, :fetch => false },
  :bm                   =>  { :uri => 'http://collection.britishmuseum.org/', :strict => false, :fetch => false },
  :archiveshub          =>  { :uri => 'http://data.archiveshub.ac.uk/def/', :source => 'http://data.archiveshub.ac.uk/def/' },
  :bibframe             =>  { :uri => 'http://bibframe.org/vocab/', :source => 'http://bibframe.org/vocab/', :strict => false, :fetch => false},
  :ccrel                =>  { :uri => 'http://creativecommons.org/ns#', :strict => false, :fetch => false },
  :mods                 =>  { :uri => 'http://www.loc.gov/standards/mods/modsrdf/v1/#', :strict => false, :fetch => false },
  :exif                 =>  { :uri => 'http://www.w3.org/2003/12/exif/ns#', :strict => false, :fetch => false},
  :schema               =>  { :uri => 'https://schema.org', :strict => false, :fetch => false},
  :vra                  =>  { :uri => 'http://opaquenamespace.org/ns/vra/', :strict => false, :fetch => false},
  :sheetmusic           =>  { :uri => 'http://opaquenamespace.org/ns/sheetmusic/', :strict => false, :fetch => false}
}
