cvs:
  creator: "Creator"
  contributor: "Contributor"
  arranger: "Arranger"
  artist: "Artist"
  author: "Author"
  composer: "Composer"
  illustrator: "Illustrator"
  lyricist: "Lyricist"
  photographer: "Photographer"
  collector: "Collector"
  lcsubject: "Lcsubject"
  militaryBranch: "Militarybranch"
  location: "Location"
  rangerdistrict: "Rangerdistrict"
  rights: "Rights"
  language: "Language"
  localcollectionname: "Localcollectionname"
  dctype: "Dc type"
  worktype: "Worktype"
  format: "Format" 
  institution: "Institution"

