default:
  jetty_port: 8983
  java_opts:
    - "-XX:MaxPermSize=128m" 
    - "-Xmx256m"
    - "-Dmarmotta.home=<%= File.expand_path(MARMOTTA_HOME) %>"
test:
  jetty_port: 8983
  startup_wait: 60
  java_opts:
    - "-XX:MaxPermSize=256m"
    - "-Xmx512m"
