default:
  startup_wait: 90
  jetty_port: 8983
  java_opts:
    - "-Xmx512m"
    - "-XX:MaxPermSize=128m"
staging:
  startup_wait: 90
  jetty_port: <%= ENV["OD2_JETTY_PORT"] || "8983" %>
  java_opts:
    - "-Xmx512m"
    - "-XX:MaxPermSize=128m"
