# -*- encoding: utf-8 -*-
# This file generated automatically using vocab-fetch from http://data.archiveshub.ac.uk/def/
require 'rdf'
module OregonDigital::Vocabularies
  class ARCHIVESHUB < RDF::StrictVocabulary("http://data.archiveshub.ac.uk/def/")

    # Class definitions
    term :ArchivalResource,
      comment: %(Recorded information in any form or medium, created or received and maintained, by an organization or person\(s\) in the transaction of business or the conduct of affairs, and maintained for its long-term research value. An archival resource may be an individual item, such as a letter or photograph, or \(more commonly\) some aggregation of such items managed and described as a unit.).freeze,
      label: "Archival Resource".freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Archival Resource).freeze,
      type: "rdfs:Class".freeze,
      "vs:term_status" => %(unstable).freeze
    term :BiographicalHistory,
      comment: %(A narrative or chronology that places archival materials in context by providing information about their creator\(s\). A finding aid may contain several such narratives or chronologies pertaining to different archival materials and their creators.).freeze,
      label: "Biographical History".freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Biographical History).freeze,
      subClassOf: ["http://purl.org/ontology/bibo/DocumentPart".freeze, "foaf:Document".freeze],
      type: "rdfs:Class".freeze,
      "vs:term_status" => %(unstable).freeze
    term :Creation,
      comment: %(An event that resulted in the creation or accumulation of an archival resource.).freeze,
      label: "Creation".freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Creation).freeze,
      subClassOf: ["http://linkedevents.org/ontology/Event".freeze, "http://purl.org/NET/c4dm/event.owl#Event".freeze],
      type: "rdfs:Class".freeze,
      "vs:term_status" => %(unstable).freeze
    term :EAD,
      comment: %(A document conforming to the Encoded Archival Description standard.).freeze,
      label: "EAD Document".freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(EAD Document).freeze,
      subClassOf: ["http://purl.org/ontology/bibo/Document".freeze, "foaf:Document".freeze],
      type: "rdfs:Class".freeze,
      "vs:term_status" => %(unstable).freeze
    term :Extent,
      comment: %(The size of an archival resource.).freeze,
      label: "Extent".freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Extent).freeze,
      subClassOf: "dc:SizeOrDuration".freeze,
      type: "rdfs:Class".freeze,
      "vs:term_status" => %(unstable).freeze
    term :Family,
      comment: %(A group of people affiliated by consanguinity, affinity, or co-residence.).freeze,
      label: "Family".freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Family).freeze,
      subClassOf: ["foaf:Group".freeze, "foaf:Agent".freeze, "dc:Agent".freeze],
      type: "rdfs:Class".freeze,
      "vs:term_status" => %(unstable).freeze
    term :FindingAid,
      comment: %(A document describing an archival resource.).freeze,
      label: "Finding Aid".freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Finding Aid).freeze,
      subClassOf: ["http://purl.org/ontology/bibo/Document".freeze, "foaf:Document".freeze],
      type: "rdfs:Class".freeze,
      "vs:term_status" => %(unstable).freeze
    term :Floruit,
      comment: %(An event corresponding to the activity of an agent.).freeze,
      label: "Floruit".freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Floruit).freeze,
      subClassOf: ["http://linkedevents.org/ontology/Event".freeze, "http://purl.org/NET/c4dm/event.owl#Event".freeze],
      type: "rdfs:Class".freeze,
      "vs:term_status" => %(unstable).freeze
    term :Function,
      comment: %(A sphere of activity or process.).freeze,
      label: "Function".freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Function).freeze,
      subClassOf: "skos:Concept".freeze,
      type: "rdfs:Class".freeze,
      "vs:term_status" => %(unstable).freeze
    term :GenreForm,
      comment: %(A category of archival material, defined either by style or technique of intellectual content, order of information or object function, or physical characteristics.).freeze,
      label: "Genre or Form".freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Genre or Form).freeze,
      subClassOf: "skos:Concept".freeze,
      type: "rdfs:Class".freeze,
      "vs:term_status" => %(unstable).freeze
    term :Level,
      comment: %(An indicator of the part of an archival collection constituted by an archival resource, whether it is the whole collection or a sub-section of it.).freeze,
      label: "Level".freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Level).freeze,
      subClassOf: "skos:Concept".freeze,
      type: "rdfs:Class".freeze,
      "vs:term_status" => %(unstable).freeze
    term :Repository,
      comment: %(An institution or agency responsible for providing access to archival materials.).freeze,
      label: "Repository".freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Repository).freeze,
      subClassOf: ["foaf:Organization".freeze, "foaf:Agent".freeze, "dc:Agent".freeze],
      type: "rdfs:Class".freeze,
      "vs:term_status" => %(unstable).freeze

    # Property definitions
    property :accessProvidedBy,
      comment: %(An agent that provides access to the resource.).freeze,
      label: "Access Provided By".freeze,
      "owl:inverseOf" => %(http://data.archiveshub.ac.uk/def/providesAccessTo).freeze,
      range: ["foaf:Agent".freeze, "dc:Agent".freeze],
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Access Provided By).freeze,
      type: "rdf:Property".freeze,
      "vs:term_status" => %(unstable).freeze
    property :accessRestrictions,
      comment: %(Access Restrictions).freeze,
      domain: "http://data.archiveshub.ac.uk/def/ArchivalResource".freeze,
      label: "Access Restrictions".freeze,
      range: "rdfs:Literal".freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Access Restrictions).freeze,
      type: "rdf:Property".freeze,
      "vs:term_status" => %(unstable).freeze
    property :accruals,
      comment: %(Accruals).freeze,
      domain: "http://data.archiveshub.ac.uk/def/ArchivalResource".freeze,
      label: "Accruals".freeze,
      range: "rdfs:Literal".freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Accruals).freeze,
      type: "rdf:Property".freeze,
      "vs:term_status" => %(unstable).freeze
    property :acquisitions,
      comment: %(Acquisitions).freeze,
      domain: "http://data.archiveshub.ac.uk/def/ArchivalResource".freeze,
      label: "Acquisitions".freeze,
      range: "rdfs:Literal".freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Acquisitions).freeze,
      type: "rdf:Property".freeze,
      "vs:term_status" => %(unstable).freeze
    property :administers,
      comment: %(A resource which the agent manages.).freeze,
      domain: ["foaf:Agent".freeze, "dc:Agent".freeze],
      label: "Administers".freeze,
      "owl:inverseOf" => %(http://data.archiveshub.ac.uk/def/isAdministeredBy).freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Administers).freeze,
      type: "rdf:Property".freeze,
      "vs:term_status" => %(unstable).freeze
    property :alternateFormsAvailable,
      comment: %(Alternate Forms Available).freeze,
      domain: "http://data.archiveshub.ac.uk/def/ArchivalResource".freeze,
      label: "Alternate Forms Available".freeze,
      range: "rdfs:Literal".freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Alternate Forms Available).freeze,
      type: "rdf:Property".freeze,
      "vs:term_status" => %(unstable).freeze
    property :appraisal,
      comment: %(Appraisal).freeze,
      domain: "http://data.archiveshub.ac.uk/def/ArchivalResource".freeze,
      label: "Appraisal".freeze,
      range: "rdfs:Literal".freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Appraisal).freeze,
      type: "rdf:Property".freeze,
      "vs:term_status" => %(unstable).freeze
    property :archbox,
      comment: %(A number of archival boxes).freeze,
      label: "Archival Box".freeze,
      range: "rdfs:Literal".freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Archival Box).freeze,
      type: "rdf:Property".freeze,
      "vs:term_status" => %(unstable).freeze
    property :associatedWith,
      comment: %(A concept adjudged by a cataloguer to have an association with an archival resource which they consider useful for the purposes of discovering that resource.).freeze,
      domain: "http://data.archiveshub.ac.uk/def/ArchivalResource".freeze,
      label: "Associated With".freeze,
      range: "skos:Concept".freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Associated With).freeze,
      type: "rdf:Property".freeze,
      "vs:term_status" => %(unstable).freeze
    property :bibliography,
      comment: %(Bibliography).freeze,
      domain: "http://data.archiveshub.ac.uk/def/ArchivalResource".freeze,
      label: "Bibliography".freeze,
      range: "rdfs:Literal".freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Bibliography).freeze,
      type: "rdf:Property".freeze,
      "vs:term_status" => %(unstable).freeze
    property :body,
      comment: %(A literal representation of the content of the document.).freeze,
      domain: ["http://purl.org/ontology/bibo/Document".freeze, "foaf:Document".freeze],
      label: "Body".freeze,
      range: "rdfs:Literal".freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Body).freeze,
      type: "rdf:Property".freeze,
      "vs:term_status" => %(unstable).freeze
    property :countryCode,
      comment: %(The ISO 3166-1 code for the country of the repository.).freeze,
      domain: "http://data.archiveshub.ac.uk/def/Repository".freeze,
      label: "Country Code".freeze,
      range: "rdfs:Literal".freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Country Code).freeze,
      type: "rdf:Property".freeze,
      "vs:term_status" => %(unstable).freeze
    property :cubicmetre,
      comment: %(A number of cubic metres).freeze,
      label: "Cubic Metre".freeze,
      range: "rdfs:Literal".freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Cubic Metre).freeze,
      type: "rdf:Property".freeze,
      "vs:term_status" => %(unstable).freeze
    property :custodialHistory,
      comment: %(Custodial History).freeze,
      domain: "http://data.archiveshub.ac.uk/def/ArchivalResource".freeze,
      label: "Custodial History".freeze,
      range: "rdfs:Literal".freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Custodial History).freeze,
      type: "rdf:Property".freeze,
      "vs:term_status" => %(unstable).freeze
    property :dateBirth,
      comment: %(The date of birth of the person.).freeze,
      domain: "foaf:Person".freeze,
      label: "Date of Birth".freeze,
      range: "rdfs:Literal".freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Date of Birth).freeze,
      type: "rdf:Property".freeze,
      "vs:term_status" => %(unstable).freeze
    property :dateCreatedAccumulated,
      comment: %(The date, represented as a typed literal, of a time interval during which the archival resource was created or accumulated.).freeze,
      label: "Date created or accumulated".freeze,
      range: "rdfs:Literal".freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Date created or accumulated).freeze,
      type: "rdf:Property".freeze,
      "vs:term_status" => %(unstable).freeze
    property :dateCreatedAccumulatedEnd,
      comment: %(The end date, represented as a typed literal, of a time interval during which the archival resource was created or accumulated.).freeze,
      label: "Date created or accumulated (end)".freeze,
      range: "rdfs:Literal".freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Date created or accumulated \(end\)).freeze,
      type: "rdf:Property".freeze,
      "vs:term_status" => %(unstable).freeze
    property :dateCreatedAccumulatedStart,
      comment: %(The start date, represented as a typed literal, of a time interval during which the archival resource was created or accumulated.).freeze,
      label: "Date created or accumulated (start)".freeze,
      range: "rdfs:Literal".freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Date created or accumulated \(start\)).freeze,
      type: "rdf:Property".freeze,
      "vs:term_status" => %(unstable).freeze
    property :dateCreatedAccumulatedString,
      comment: %(The date, represented as a string, of a time interval during which the archival resource was created or accumulated.).freeze,
      label: "Date created or accumulated".freeze,
      range: "rdfs:Literal".freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Date created or accumulated).freeze,
      type: "rdf:Property".freeze,
      "vs:term_status" => %(unstable).freeze
    property :dateDeath,
      comment: %(The date of death of the person.).freeze,
      domain: "foaf:Person".freeze,
      label: "Date of Death".freeze,
      range: "rdfs:Literal".freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Date of Death).freeze,
      type: "rdf:Property".freeze,
      "vs:term_status" => %(unstable).freeze
    property :dates,
      comment: %(Dates).freeze,
      label: "Dates".freeze,
      range: "rdfs:Literal".freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Dates).freeze,
      type: "rdf:Property".freeze,
      "vs:term_status" => %(unstable).freeze
    property :encodedAs,
      comment: %(An EAD document that is an encoding of the archival finding aid.).freeze,
      domain: "http://data.archiveshub.ac.uk/def/FindingAid".freeze,
      label: "Encoded As".freeze,
      "owl:inverseOf" => %(http://data.archiveshub.ac.uk/def/encodingOf).freeze,
      range: "http://data.archiveshub.ac.uk/def/EAD".freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Encoded As).freeze,
      type: "rdf:Property".freeze,
      "vs:term_status" => %(unstable).freeze
    property :encodingOf,
      comment: %(An archival finding aid of which the EAD document is an encoding.).freeze,
      domain: "http://data.archiveshub.ac.uk/def/EAD".freeze,
      label: "Encoding Of".freeze,
      "owl:inverseOf" => %(http://data.archiveshub.ac.uk/def/encodedAs).freeze,
      range: "http://data.archiveshub.ac.uk/def/FindingAid".freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Encoding Of).freeze,
      type: "rdf:Property".freeze,
      "vs:term_status" => %(unstable).freeze
    property :envelope,
      comment: %(A number of envelopes).freeze,
      label: "Envelope".freeze,
      range: "rdfs:Literal".freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Envelope).freeze,
      type: "rdf:Property".freeze,
      "vs:term_status" => %(unstable).freeze
    property :epithet,
      comment: %(Epithet).freeze,
      label: "Epithet".freeze,
      range: "rdfs:Literal".freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Epithet).freeze,
      type: "rdf:Property".freeze,
      "vs:term_status" => %(unstable).freeze
    property :extent,
      comment: %(The size of the archival resource.).freeze,
      domain: "http://data.archiveshub.ac.uk/def/ArchivalResource".freeze,
      label: "Extent".freeze,
      range: "rdfs:Literal".freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Extent).freeze,
      type: "rdf:Property".freeze,
      "vs:term_status" => %(unstable).freeze
    property :file,
      comment: %(A number of files).freeze,
      label: "File".freeze,
      range: "rdfs:Literal".freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(File).freeze,
      type: "rdf:Property".freeze,
      "vs:term_status" => %(unstable).freeze
    property :folder,
      comment: %(A number of folders).freeze,
      label: "Folder".freeze,
      range: "rdfs:Literal".freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Folder).freeze,
      type: "rdf:Property".freeze,
      "vs:term_status" => %(unstable).freeze
    property :forename,
      comment: %(The forename of a person who is the focus of the concept).freeze,
      label: "Forename".freeze,
      range: "rdfs:Literal".freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Forename).freeze,
      type: "rdf:Property".freeze,
      "vs:term_status" => %(unstable).freeze
    property :hasBiographicalHistory,
      comment: %(A narrative or chronology that places archival materials in context by providing information about their creator\(s\).).freeze,
      domain: "http://data.archiveshub.ac.uk/def/ArchivalResource".freeze,
      label: "Has Biographical History".freeze,
      "owl:inverseOf" => %(http://data.archiveshub.ac.uk/def/isBiographicalHistoryFor).freeze,
      range: "http://data.archiveshub.ac.uk/def/BiographicalHistory".freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Has Biographical History).freeze,
      type: "rdf:Property".freeze,
      "vs:term_status" => %(unstable).freeze
    property :isAdministeredBy,
      comment: %(An agent that manages the resource.).freeze,
      label: "Is Administered By".freeze,
      "owl:inverseOf" => %(http://data.archiveshub.ac.uk/def/administers).freeze,
      range: ["foaf:Agent".freeze, "dc:Agent".freeze],
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Is Administered By).freeze,
      type: "rdf:Property".freeze,
      "vs:term_status" => %(unstable).freeze
    property :isBiographicalHistoryFor,
      comment: %(An archival resource that the narrative or chronology places in context by providing information about their creator\(s\).).freeze,
      domain: "http://data.archiveshub.ac.uk/def/BiographicalHistory".freeze,
      label: "Is Biographical History For".freeze,
      "owl:inverseOf" => %(http://data.archiveshub.ac.uk/def/hasBiographicalHistory).freeze,
      range: "http://data.archiveshub.ac.uk/def/ArchivalResource".freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Is Biographical History For).freeze,
      type: "rdf:Property".freeze,
      "vs:term_status" => %(unstable).freeze
    property :isMaintenanceAgencyOf,
      comment: %(An archival finding aid for which the repository is responsible for the maintenance.).freeze,
      domain: "http://data.archiveshub.ac.uk/def/Repository".freeze,
      label: "Is Maintenance Agency Of".freeze,
      "owl:inverseOf" => %(http://data.archiveshub.ac.uk/def/maintenanceAgency).freeze,
      range: "http://data.archiveshub.ac.uk/def/FindingAid".freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Is Maintenance Agency Of).freeze,
      type: "rdf:Property".freeze,
      "vs:term_status" => %(unstable).freeze
    property :isOriginationOf,
      comment: %(An archival resource for which the agent is responsible for the creation or accumulation.).freeze,
      domain: ["foaf:Agent".freeze, "dc:Agent".freeze],
      label: "Is Origination Of".freeze,
      "owl:inverseOf" => %(http://data.archiveshub.ac.uk/def/origination).freeze,
      range: "http://data.archiveshub.ac.uk/def/ArchivalResource".freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Is Origination Of).freeze,
      type: "rdf:Property".freeze,
      "vs:term_status" => %(unstable).freeze
    property :isPublisherOf,
      comment: %(A resource which the agent makes available.).freeze,
      domain: ["foaf:Agent".freeze, "dc:Agent".freeze],
      label: "Is Publisher Of".freeze,
      "owl:inverseOf" => %(dc:publisher).freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Is Publisher Of).freeze,
      type: "rdf:Property".freeze,
      "vs:term_status" => %(unstable).freeze
    property :isRepresentedBy,
      comment: [%(A resource which represents the archival resource, such as an image of a text page, a transcription of text, an audio or video clip, or an aggregation of such resources.).freeze, %(An archival resourcce represented by the resource.).freeze],
      domain: "http://data.archiveshub.ac.uk/def/ArchivalResource".freeze,
      label: "Is Represented By".freeze,
      range: "http://data.archiveshub.ac.uk/def/ArchivalResource".freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Is Represented By).freeze,
      type: "rdf:Property".freeze,
      "vs:term_status" => %(unstable).freeze
    property :item,
      comment: %(A number of items).freeze,
      label: "Item".freeze,
      range: "rdfs:Literal".freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Item).freeze,
      type: "rdf:Property".freeze,
      "vs:term_status" => %(unstable).freeze
    property :level,
      comment: %(An indicator of the part of an archival collection constituted by an archival resource.).freeze,
      domain: "http://data.archiveshub.ac.uk/def/ArchivalResource".freeze,
      label: "Level".freeze,
      range: "http://data.archiveshub.ac.uk/def/Level".freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Level).freeze,
      type: "rdf:Property".freeze,
      "vs:term_status" => %(unstable).freeze
    property :location,
      comment: %(Location).freeze,
      label: "Location".freeze,
      range: "rdfs:Literal".freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Location).freeze,
      type: "rdf:Property".freeze,
      "vs:term_status" => %(unstable).freeze
    property :locationOfOriginals,
      comment: %(Location of Originals).freeze,
      domain: "http://data.archiveshub.ac.uk/def/ArchivalResource".freeze,
      label: "Location of Originals".freeze,
      range: "rdfs:Literal".freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Location of Originals).freeze,
      type: "rdf:Property".freeze,
      "vs:term_status" => %(unstable).freeze
    property :maintenanceAgency,
      comment: %(A repository responsible for the maintenance of the archival finding aid.).freeze,
      domain: "http://data.archiveshub.ac.uk/def/FindingAid".freeze,
      label: "Maintenance Agency".freeze,
      "owl:inverseOf" => %(http://data.archiveshub.ac.uk/def/isMaintenanceAgencyOf).freeze,
      range: "http://data.archiveshub.ac.uk/def/Repository".freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Maintenance Agency).freeze,
      type: "rdf:Property".freeze,
      "vs:term_status" => %(unstable).freeze
    property :maintenanceAgencyCode,
      comment: %(The ISO 15511 code for the repository.).freeze,
      domain: "http://data.archiveshub.ac.uk/def/Repository".freeze,
      label: "Maintenance Agency Code".freeze,
      range: "rdfs:Literal".freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Maintenance Agency Code).freeze,
      type: "rdf:Property".freeze,
      "vs:term_status" => %(unstable).freeze
    property :members,
      comment: %(Members).freeze,
      domain: "http://data.archiveshub.ac.uk/def/ArchivalResource".freeze,
      label: "Members".freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Members).freeze,
      type: "rdf:Property".freeze,
      "vs:term_status" => %(unstable).freeze
    property :metre,
      comment: %(A number of metres).freeze,
      label: "Metre".freeze,
      range: "rdfs:Literal".freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Metre).freeze,
      type: "rdf:Property".freeze,
      "vs:term_status" => %(unstable).freeze
    property :name,
      comment: %(Name).freeze,
      label: "Name".freeze,
      range: "rdfs:Literal".freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Name).freeze,
      type: "rdf:Property".freeze,
      "vs:term_status" => %(unstable).freeze
    property :note,
      comment: %(Note).freeze,
      domain: "http://data.archiveshub.ac.uk/def/ArchivalResource".freeze,
      label: "Note".freeze,
      range: "rdfs:Literal".freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Note).freeze,
      type: "rdf:Property".freeze,
      "vs:term_status" => %(unstable).freeze
    property :origination,
      comment: %(An agent responsible for the creation or accumulation of the archival resource.).freeze,
      domain: "http://data.archiveshub.ac.uk/def/ArchivalResource".freeze,
      label: "Origination".freeze,
      "owl:inverseOf" => %(http://data.archiveshub.ac.uk/def/isOriginationOf).freeze,
      range: ["foaf:Agent".freeze, "dc:Agent".freeze],
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Origination).freeze,
      type: "rdf:Property".freeze,
      "vs:term_status" => %(unstable).freeze
    property :other,
      comment: %(Other).freeze,
      label: "Other".freeze,
      range: "rdfs:Literal".freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Other).freeze,
      type: "rdf:Property".freeze,
      "vs:term_status" => %(unstable).freeze
    property :otherFindingAids,
      comment: %(Other Finding Aids).freeze,
      domain: "http://data.archiveshub.ac.uk/def/ArchivalResource".freeze,
      label: "Other Finding Aids".freeze,
      range: "rdfs:Literal".freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Other Finding Aids).freeze,
      type: "rdf:Property".freeze,
      "vs:term_status" => %(unstable).freeze
    property :page,
      comment: %(A number of pages).freeze,
      label: "Page".freeze,
      range: "rdfs:Literal".freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Page).freeze,
      type: "rdf:Property".freeze,
      "vs:term_status" => %(unstable).freeze
    property :paper,
      comment: %(A number of papers).freeze,
      label: "Paper".freeze,
      range: "rdfs:Literal".freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Paper).freeze,
      type: "rdf:Property".freeze,
      "vs:term_status" => %(unstable).freeze
    property :physicalTechnicalRequirements,
      comment: %(Physical and Technical Requirements).freeze,
      domain: "http://data.archiveshub.ac.uk/def/ArchivalResource".freeze,
      label: "Physical and Technical Requirements".freeze,
      range: "rdfs:Literal".freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Physical and Technical Requirements).freeze,
      type: "rdf:Property".freeze,
      "vs:term_status" => %(unstable).freeze
    property :processing,
      comment: %(Processing).freeze,
      domain: "http://data.archiveshub.ac.uk/def/ArchivalResource".freeze,
      label: "Processing".freeze,
      range: "rdfs:Literal".freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Processing).freeze,
      type: "rdf:Property".freeze,
      "vs:term_status" => %(unstable).freeze
    property :providesAccessTo,
      comment: %(A resource to which the agent provides access.).freeze,
      domain: ["foaf:Agent".freeze, "dc:Agent".freeze],
      label: "Provides Access To".freeze,
      "owl:inverseOf" => %(http://data.archiveshub.ac.uk/def/accessProvidedBy).freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Provides Access To).freeze,
      type: "rdf:Property".freeze,
      "vs:term_status" => %(unstable).freeze
    property :relatedMaterial,
      comment: %(Related Material).freeze,
      domain: "http://data.archiveshub.ac.uk/def/ArchivalResource".freeze,
      label: "Related Material".freeze,
      range: "rdfs:Literal".freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Related Material).freeze,
      type: "rdf:Property".freeze,
      "vs:term_status" => %(unstable).freeze
    property :scopecontent,
      comment: %(Scope and Content).freeze,
      domain: "http://data.archiveshub.ac.uk/def/ArchivalResource".freeze,
      label: "Scope and Content".freeze,
      range: "rdfs:Literal".freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Scope and Content).freeze,
      type: "rdf:Property".freeze,
      "vs:term_status" => %(unstable).freeze
    property :surname,
      comment: %(The surname of a person who is the focus of the concept).freeze,
      label: "Surname".freeze,
      range: "rdfs:Literal".freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Surname).freeze,
      type: "rdf:Property".freeze,
      "vs:term_status" => %(unstable).freeze
    property :title,
      comment: %(The title of a person who is the focus of the concept).freeze,
      label: "Title".freeze,
      range: "rdfs:Literal".freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Title).freeze,
      type: "rdf:Property".freeze,
      "vs:term_status" => %(unstable).freeze
    property :useRestrictions,
      comment: %(Use Restrictions).freeze,
      domain: "http://data.archiveshub.ac.uk/def/ArchivalResource".freeze,
      label: "Use Restrictions".freeze,
      range: "rdfs:Literal".freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Use Restrictions).freeze,
      type: "rdf:Property".freeze,
      "vs:term_status" => %(unstable).freeze
    property :volume,
      comment: %(A number of volumes).freeze,
      label: "Volume".freeze,
      range: "rdfs:Literal".freeze,
      "rdfs:isDefinedBy" => %(http://data.archiveshub.ac.uk/def/).freeze,
      "skos:prefLabel" => %(Volume).freeze,
      type: "rdf:Property".freeze,
      "vs:term_status" => %(unstable).freeze

    # Extra definitions
    term :"",
      comment: %(The LOCAH RDF Vocabulary).freeze,
      "http://purl.org/NET/c4dm/event.owl#produced_in" => %(http://data.archiveshub.ac.uk/id/project/locah).freeze,
      label: "The LOCAH RDF Vocabulary".freeze,
      "skos:prefLabel" => %(The LOCAH RDF Vocabulary).freeze
  end
end
