# -*- encoding: utf-8 -*-
# This file generated automatically using vocab-fetch from http://id.loc.gov/vocabulary/iso639-1.nt
require 'rdf'
module OregonDigital::Vocabularies
  class ISO_639_1 < RDF::StrictVocabulary("http://id.loc.gov/vocabulary/iso639-1/")

    # Extra definitions
    term :aa,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Afar).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(aa).freeze,
      label: "Afar".freeze,
      "skos:notation" => %(aa).freeze,
      "skos:prefLabel" => %(Afar).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :ab,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Abkhazian).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(ab).freeze,
      label: "Abkhazian".freeze,
      "skos:notation" => %(ab).freeze,
      "skos:prefLabel" => %(Abkhazian).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :ae,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Avestan).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(ae).freeze,
      label: "Avestan".freeze,
      "skos:notation" => %(ae).freeze,
      "skos:prefLabel" => %(Avestan).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :af,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Afrikaans).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(af).freeze,
      label: "Afrikaans".freeze,
      "skos:notation" => %(af).freeze,
      "skos:prefLabel" => %(Afrikaans).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :ak,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Akan).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(ak).freeze,
      label: "Akan".freeze,
      "skos:notation" => %(ak).freeze,
      "skos:prefLabel" => %(Akan).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :am,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Amharic).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(am).freeze,
      label: "Amharic".freeze,
      "skos:notation" => %(am).freeze,
      "skos:prefLabel" => %(Amharic).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :an,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Aragonese).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(an).freeze,
      label: "Aragonese".freeze,
      "skos:notation" => %(an).freeze,
      "skos:prefLabel" => %(Aragonese).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :ar,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Arabic).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(ar).freeze,
      label: "Arabic".freeze,
      "skos:notation" => %(ar).freeze,
      "skos:prefLabel" => %(Arabic).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :as,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Assamese).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(as).freeze,
      label: "Assamese".freeze,
      "skos:notation" => %(as).freeze,
      "skos:prefLabel" => %(Assamese).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :av,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Avaric).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(av).freeze,
      label: "Avaric".freeze,
      "skos:notation" => %(av).freeze,
      "skos:prefLabel" => %(Avaric).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :ay,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Aymara).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(ay).freeze,
      label: "Aymara".freeze,
      "skos:notation" => %(ay).freeze,
      "skos:prefLabel" => %(Aymara).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :az,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Azerbaijani).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(az).freeze,
      label: "Azerbaijani".freeze,
      "skos:notation" => %(az).freeze,
      "skos:prefLabel" => %(Azerbaijani).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :ba,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Bashkir).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(ba).freeze,
      label: "Bashkir".freeze,
      "skos:notation" => %(ba).freeze,
      "skos:prefLabel" => %(Bashkir).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :be,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Belarusian).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(be).freeze,
      label: "Belarusian".freeze,
      "skos:notation" => %(be).freeze,
      "skos:prefLabel" => %(Belarusian).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :bg,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Bulgarian).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(bg).freeze,
      label: "Bulgarian".freeze,
      "skos:notation" => %(bg).freeze,
      "skos:prefLabel" => %(Bulgarian).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :bh,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Bihari languages).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(bh).freeze,
      label: "Bihari languages".freeze,
      "skos:notation" => %(bh).freeze,
      "skos:prefLabel" => %(Bihari languages).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :bi,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Bislama).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(bi).freeze,
      label: "Bislama".freeze,
      "skos:notation" => %(bi).freeze,
      "skos:prefLabel" => %(Bislama).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :bm,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Bambara).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(bm).freeze,
      label: "Bambara".freeze,
      "skos:notation" => %(bm).freeze,
      "skos:prefLabel" => %(Bambara).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :bn,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Bengali).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(bn).freeze,
      label: "Bengali".freeze,
      "skos:notation" => %(bn).freeze,
      "skos:prefLabel" => %(Bengali).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :bo,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Tibetan).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(bo).freeze,
      label: "Tibetan".freeze,
      "skos:notation" => %(bo).freeze,
      "skos:prefLabel" => %(Tibetan).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :br,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Breton).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(br).freeze,
      label: "Breton".freeze,
      "skos:notation" => %(br).freeze,
      "skos:prefLabel" => %(Breton).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :bs,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Bosnian).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(bs).freeze,
      label: "Bosnian".freeze,
      "skos:notation" => %(bs).freeze,
      "skos:prefLabel" => %(Bosnian).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :ca,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Catalan |  Valencian).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(ca).freeze,
      label: ["Catalan |  Valencian".freeze, "Catalan | Valencian".freeze],
      "skos:notation" => %(ca).freeze,
      "skos:prefLabel" => %(Catalan | Valencian).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :ce,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Chechen).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(ce).freeze,
      label: "Chechen".freeze,
      "skos:notation" => %(ce).freeze,
      "skos:prefLabel" => %(Chechen).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :ch,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Chamorro).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(ch).freeze,
      label: "Chamorro".freeze,
      "skos:notation" => %(ch).freeze,
      "skos:prefLabel" => %(Chamorro).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :co,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Corsican).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(co).freeze,
      label: "Corsican".freeze,
      "skos:notation" => %(co).freeze,
      "skos:prefLabel" => %(Corsican).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :cr,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Cree).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(cr).freeze,
      label: "Cree".freeze,
      "skos:notation" => %(cr).freeze,
      "skos:prefLabel" => %(Cree).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :cs,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Czech).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(cs).freeze,
      label: "Czech".freeze,
      "skos:notation" => %(cs).freeze,
      "skos:prefLabel" => %(Czech).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :cu,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Church Slavic |  Old Slavonic |  Church Slavonic |  Old Bulgarian |  Old Church Slavonic).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(cu).freeze,
      label: ["Church Slavic |  Old Slavonic |  Church Slavonic |  Old Bulgarian |  Old Church Slavonic".freeze, "Church Slavic | Old Slavonic | Church Slavonic | Old Bulgarian | Old Church Slavonic".freeze],
      "skos:notation" => %(cu).freeze,
      "skos:prefLabel" => %(Church Slavic | Old Slavonic | Church Slavonic | Old Bulgarian | Old Church Slavonic).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :cv,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Chuvash).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(cv).freeze,
      label: "Chuvash".freeze,
      "skos:notation" => %(cv).freeze,
      "skos:prefLabel" => %(Chuvash).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :cy,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Welsh).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(cy).freeze,
      label: "Welsh".freeze,
      "skos:notation" => %(cy).freeze,
      "skos:prefLabel" => %(Welsh).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :da,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Danish).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(da).freeze,
      label: "Danish".freeze,
      "skos:notation" => %(da).freeze,
      "skos:prefLabel" => %(Danish).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :de,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(German).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(de).freeze,
      label: "German".freeze,
      "skos:notation" => %(de).freeze,
      "skos:prefLabel" => %(German).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :dv,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Divehi |  Dhivehi |  Maldivian).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(dv).freeze,
      label: ["Divehi |  Dhivehi |  Maldivian".freeze, "Divehi | Dhivehi | Maldivian".freeze],
      "skos:notation" => %(dv).freeze,
      "skos:prefLabel" => %(Divehi | Dhivehi | Maldivian).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :dz,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Dzongkha).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(dz).freeze,
      label: "Dzongkha".freeze,
      "skos:notation" => %(dz).freeze,
      "skos:prefLabel" => %(Dzongkha).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :ee,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Ewe).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(ee).freeze,
      label: "Ewe".freeze,
      "skos:notation" => %(ee).freeze,
      "skos:prefLabel" => %(Ewe).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :el,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Greek, Modern \(1453-\)).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(el).freeze,
      label: "Greek, Modern (1453-)".freeze,
      "skos:notation" => %(el).freeze,
      "skos:prefLabel" => %(Greek, Modern \(1453-\)).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :en,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(English).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(en).freeze,
      label: "English".freeze,
      "skos:notation" => %(en).freeze,
      "skos:prefLabel" => %(English).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :eo,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Esperanto).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(eo).freeze,
      label: "Esperanto".freeze,
      "skos:notation" => %(eo).freeze,
      "skos:prefLabel" => %(Esperanto).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :es,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Spanish |  Castilian).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(es).freeze,
      label: ["Spanish |  Castilian".freeze, "Spanish | Castilian".freeze],
      "skos:notation" => %(es).freeze,
      "skos:prefLabel" => %(Spanish | Castilian).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :et,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Estonian).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(et).freeze,
      label: "Estonian".freeze,
      "skos:notation" => %(et).freeze,
      "skos:prefLabel" => %(Estonian).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :eu,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Basque).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(eu).freeze,
      label: "Basque".freeze,
      "skos:notation" => %(eu).freeze,
      "skos:prefLabel" => %(Basque).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :fa,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Persian).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(fa).freeze,
      label: "Persian".freeze,
      "skos:notation" => %(fa).freeze,
      "skos:prefLabel" => %(Persian).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :ff,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Fulah).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(ff).freeze,
      label: "Fulah".freeze,
      "skos:notation" => %(ff).freeze,
      "skos:prefLabel" => %(Fulah).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :fi,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Finnish).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(fi).freeze,
      label: "Finnish".freeze,
      "skos:notation" => %(fi).freeze,
      "skos:prefLabel" => %(Finnish).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :fj,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Fijian).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(fj).freeze,
      label: "Fijian".freeze,
      "skos:notation" => %(fj).freeze,
      "skos:prefLabel" => %(Fijian).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :fo,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Faroese).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(fo).freeze,
      label: "Faroese".freeze,
      "skos:notation" => %(fo).freeze,
      "skos:prefLabel" => %(Faroese).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :fr,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(French).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(fr).freeze,
      label: "French".freeze,
      "skos:notation" => %(fr).freeze,
      "skos:prefLabel" => %(French).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :fy,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Western Frisian).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(fy).freeze,
      label: "Western Frisian".freeze,
      "skos:notation" => %(fy).freeze,
      "skos:prefLabel" => %(Western Frisian).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :ga,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Irish).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(ga).freeze,
      label: "Irish".freeze,
      "skos:notation" => %(ga).freeze,
      "skos:prefLabel" => %(Irish).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :gd,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Gaelic |  Scottish Gaelic).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(gd).freeze,
      label: ["Gaelic |  Scottish Gaelic".freeze, "Gaelic | Scottish Gaelic".freeze],
      "skos:notation" => %(gd).freeze,
      "skos:prefLabel" => %(Gaelic | Scottish Gaelic).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :gl,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Galician).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(gl).freeze,
      label: "Galician".freeze,
      "skos:notation" => %(gl).freeze,
      "skos:prefLabel" => %(Galician).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :gn,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Guarani).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(gn).freeze,
      label: "Guarani".freeze,
      "skos:notation" => %(gn).freeze,
      "skos:prefLabel" => %(Guarani).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :gu,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Gujarati).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(gu).freeze,
      label: "Gujarati".freeze,
      "skos:notation" => %(gu).freeze,
      "skos:prefLabel" => %(Gujarati).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :gv,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Manx).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(gv).freeze,
      label: "Manx".freeze,
      "skos:notation" => %(gv).freeze,
      "skos:prefLabel" => %(Manx).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :ha,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Hausa).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(ha).freeze,
      label: "Hausa".freeze,
      "skos:notation" => %(ha).freeze,
      "skos:prefLabel" => %(Hausa).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :he,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Hebrew).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(he).freeze,
      label: "Hebrew".freeze,
      "skos:notation" => %(he).freeze,
      "skos:prefLabel" => %(Hebrew).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :hi,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Hindi).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(hi).freeze,
      label: "Hindi".freeze,
      "skos:notation" => %(hi).freeze,
      "skos:prefLabel" => %(Hindi).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :ho,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Hiri Motu).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(ho).freeze,
      label: "Hiri Motu".freeze,
      "skos:notation" => %(ho).freeze,
      "skos:prefLabel" => %(Hiri Motu).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :hr,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Croatian).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(hr).freeze,
      label: "Croatian".freeze,
      "skos:notation" => %(hr).freeze,
      "skos:prefLabel" => %(Croatian).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :ht,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Haitian |  Haitian Creole).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(ht).freeze,
      label: ["Haitian |  Haitian Creole".freeze, "Haitian | Haitian Creole".freeze],
      "skos:notation" => %(ht).freeze,
      "skos:prefLabel" => %(Haitian | Haitian Creole).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :hu,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Hungarian).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(hu).freeze,
      label: "Hungarian".freeze,
      "skos:notation" => %(hu).freeze,
      "skos:prefLabel" => %(Hungarian).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :hy,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Armenian).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(hy).freeze,
      label: "Armenian".freeze,
      "skos:notation" => %(hy).freeze,
      "skos:prefLabel" => %(Armenian).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :hz,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Herero).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(hz).freeze,
      label: "Herero".freeze,
      "skos:notation" => %(hz).freeze,
      "skos:prefLabel" => %(Herero).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :ia,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Interlingua \(International Auxiliary Language Association\)).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(ia).freeze,
      label: "Interlingua (International Auxiliary Language Association)".freeze,
      "skos:notation" => %(ia).freeze,
      "skos:prefLabel" => %(Interlingua \(International Auxiliary Language Association\)).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :id,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Indonesian).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(id).freeze,
      label: "Indonesian".freeze,
      "skos:notation" => %(id).freeze,
      "skos:prefLabel" => %(Indonesian).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :ie,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Interlingue |  Occidental).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(ie).freeze,
      label: ["Interlingue |  Occidental".freeze, "Interlingue | Occidental".freeze],
      "skos:notation" => %(ie).freeze,
      "skos:prefLabel" => %(Interlingue | Occidental).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :ig,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Igbo).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(ig).freeze,
      label: "Igbo".freeze,
      "skos:notation" => %(ig).freeze,
      "skos:prefLabel" => %(Igbo).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :ii,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Sichuan Yi |  Nuosu).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(ii).freeze,
      label: ["Sichuan Yi |  Nuosu".freeze, "Sichuan Yi | Nuosu".freeze],
      "skos:notation" => %(ii).freeze,
      "skos:prefLabel" => %(Sichuan Yi | Nuosu).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :ik,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Inupiaq).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(ik).freeze,
      label: "Inupiaq".freeze,
      "skos:notation" => %(ik).freeze,
      "skos:prefLabel" => %(Inupiaq).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :io,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Ido).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(io).freeze,
      label: "Ido".freeze,
      "skos:notation" => %(io).freeze,
      "skos:prefLabel" => %(Ido).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :is,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Icelandic).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(is).freeze,
      label: "Icelandic".freeze,
      "skos:notation" => %(is).freeze,
      "skos:prefLabel" => %(Icelandic).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :it,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Italian).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(it).freeze,
      label: "Italian".freeze,
      "skos:notation" => %(it).freeze,
      "skos:prefLabel" => %(Italian).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :iu,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Inuktitut).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(iu).freeze,
      label: "Inuktitut".freeze,
      "skos:notation" => %(iu).freeze,
      "skos:prefLabel" => %(Inuktitut).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :ja,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Japanese).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(ja).freeze,
      label: "Japanese".freeze,
      "skos:notation" => %(ja).freeze,
      "skos:prefLabel" => %(Japanese).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :jv,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Javanese).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(jv).freeze,
      label: "Javanese".freeze,
      "skos:notation" => %(jv).freeze,
      "skos:prefLabel" => %(Javanese).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :ka,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Georgian).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(ka).freeze,
      label: "Georgian".freeze,
      "skos:notation" => %(ka).freeze,
      "skos:prefLabel" => %(Georgian).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :kg,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Kongo).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(kg).freeze,
      label: "Kongo".freeze,
      "skos:notation" => %(kg).freeze,
      "skos:prefLabel" => %(Kongo).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :ki,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Kikuyu |  Gikuyu).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(ki).freeze,
      label: ["Kikuyu |  Gikuyu".freeze, "Kikuyu | Gikuyu".freeze],
      "skos:notation" => %(ki).freeze,
      "skos:prefLabel" => %(Kikuyu | Gikuyu).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :kj,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Kuanyama |  Kwanyama).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(kj).freeze,
      label: ["Kuanyama |  Kwanyama".freeze, "Kuanyama | Kwanyama".freeze],
      "skos:notation" => %(kj).freeze,
      "skos:prefLabel" => %(Kuanyama | Kwanyama).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :kk,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Kazakh).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(kk).freeze,
      label: "Kazakh".freeze,
      "skos:notation" => %(kk).freeze,
      "skos:prefLabel" => %(Kazakh).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :kl,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Kalaallisut |  Greenlandic).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(kl).freeze,
      label: ["Kalaallisut |  Greenlandic".freeze, "Kalaallisut | Greenlandic".freeze],
      "skos:notation" => %(kl).freeze,
      "skos:prefLabel" => %(Kalaallisut | Greenlandic).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :km,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Central Khmer).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(km).freeze,
      label: "Central Khmer".freeze,
      "skos:notation" => %(km).freeze,
      "skos:prefLabel" => %(Central Khmer).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :kn,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Kannada).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(kn).freeze,
      label: "Kannada".freeze,
      "skos:notation" => %(kn).freeze,
      "skos:prefLabel" => %(Kannada).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :ko,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Korean).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(ko).freeze,
      label: "Korean".freeze,
      "skos:notation" => %(ko).freeze,
      "skos:prefLabel" => %(Korean).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :kr,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Kanuri).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(kr).freeze,
      label: "Kanuri".freeze,
      "skos:notation" => %(kr).freeze,
      "skos:prefLabel" => %(Kanuri).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :ks,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Kashmiri).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(ks).freeze,
      label: "Kashmiri".freeze,
      "skos:notation" => %(ks).freeze,
      "skos:prefLabel" => %(Kashmiri).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :ku,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Kurdish).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(ku).freeze,
      label: "Kurdish".freeze,
      "skos:notation" => %(ku).freeze,
      "skos:prefLabel" => %(Kurdish).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :kv,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Komi).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(kv).freeze,
      label: "Komi".freeze,
      "skos:notation" => %(kv).freeze,
      "skos:prefLabel" => %(Komi).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :kw,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Cornish).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(kw).freeze,
      label: "Cornish".freeze,
      "skos:notation" => %(kw).freeze,
      "skos:prefLabel" => %(Cornish).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :ky,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Kirghiz |  Kyrgyz).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(ky).freeze,
      label: ["Kirghiz |  Kyrgyz".freeze, "Kirghiz | Kyrgyz".freeze],
      "skos:notation" => %(ky).freeze,
      "skos:prefLabel" => %(Kirghiz | Kyrgyz).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :la,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Latin).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(la).freeze,
      label: "Latin".freeze,
      "skos:notation" => %(la).freeze,
      "skos:prefLabel" => %(Latin).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :lb,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Luxembourgish |  Letzeburgesch).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(lb).freeze,
      label: ["Luxembourgish |  Letzeburgesch".freeze, "Luxembourgish | Letzeburgesch".freeze],
      "skos:notation" => %(lb).freeze,
      "skos:prefLabel" => %(Luxembourgish | Letzeburgesch).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :lg,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Ganda).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(lg).freeze,
      label: "Ganda".freeze,
      "skos:notation" => %(lg).freeze,
      "skos:prefLabel" => %(Ganda).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :li,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Limburgan |  Limburger |  Limburgish).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(li).freeze,
      label: ["Limburgan |  Limburger |  Limburgish".freeze, "Limburgan | Limburger | Limburgish".freeze],
      "skos:notation" => %(li).freeze,
      "skos:prefLabel" => %(Limburgan | Limburger | Limburgish).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :ln,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Lingala).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(ln).freeze,
      label: "Lingala".freeze,
      "skos:notation" => %(ln).freeze,
      "skos:prefLabel" => %(Lingala).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :lo,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Lao).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(lo).freeze,
      label: "Lao".freeze,
      "skos:notation" => %(lo).freeze,
      "skos:prefLabel" => %(Lao).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :lt,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Lithuanian).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(lt).freeze,
      label: "Lithuanian".freeze,
      "skos:notation" => %(lt).freeze,
      "skos:prefLabel" => %(Lithuanian).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :lu,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Luba-Katanga).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(lu).freeze,
      label: "Luba-Katanga".freeze,
      "skos:notation" => %(lu).freeze,
      "skos:prefLabel" => %(Luba-Katanga).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :lv,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Latvian).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(lv).freeze,
      label: "Latvian".freeze,
      "skos:notation" => %(lv).freeze,
      "skos:prefLabel" => %(Latvian).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :mg,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Malagasy).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(mg).freeze,
      label: "Malagasy".freeze,
      "skos:notation" => %(mg).freeze,
      "skos:prefLabel" => %(Malagasy).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :mh,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Marshallese).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(mh).freeze,
      label: "Marshallese".freeze,
      "skos:notation" => %(mh).freeze,
      "skos:prefLabel" => %(Marshallese).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :mi,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Maori).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(mi).freeze,
      label: "Maori".freeze,
      "skos:notation" => %(mi).freeze,
      "skos:prefLabel" => %(Maori).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :mk,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Macedonian).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(mk).freeze,
      label: "Macedonian".freeze,
      "skos:notation" => %(mk).freeze,
      "skos:prefLabel" => %(Macedonian).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :ml,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Malayalam).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(ml).freeze,
      label: "Malayalam".freeze,
      "skos:notation" => %(ml).freeze,
      "skos:prefLabel" => %(Malayalam).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :mn,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Mongolian).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(mn).freeze,
      label: "Mongolian".freeze,
      "skos:notation" => %(mn).freeze,
      "skos:prefLabel" => %(Mongolian).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :mr,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Marathi).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(mr).freeze,
      label: "Marathi".freeze,
      "skos:notation" => %(mr).freeze,
      "skos:prefLabel" => %(Marathi).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :ms,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Malay).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(ms).freeze,
      label: "Malay".freeze,
      "skos:notation" => %(ms).freeze,
      "skos:prefLabel" => %(Malay).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :mt,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Maltese).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(mt).freeze,
      label: "Maltese".freeze,
      "skos:notation" => %(mt).freeze,
      "skos:prefLabel" => %(Maltese).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :my,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Burmese).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(my).freeze,
      label: "Burmese".freeze,
      "skos:notation" => %(my).freeze,
      "skos:prefLabel" => %(Burmese).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :na,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Nauru).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(na).freeze,
      label: "Nauru".freeze,
      "skos:notation" => %(na).freeze,
      "skos:prefLabel" => %(Nauru).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :nb,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Bokmål, Norwegian |  Norwegian Bokmål).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(nb).freeze,
      label: ["Bokmål, Norwegian |  Norwegian Bokmål".freeze, "Bokmål, Norwegian | Norwegian Bokmål".freeze],
      "skos:notation" => %(nb).freeze,
      "skos:prefLabel" => %(Bokmål, Norwegian | Norwegian Bokmål).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :nd,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Ndebele, North |  North Ndebele).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(nd).freeze,
      label: ["Ndebele, North |  North Ndebele".freeze, "Ndebele, North | North Ndebele".freeze],
      "skos:notation" => %(nd).freeze,
      "skos:prefLabel" => %(Ndebele, North | North Ndebele).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :ne,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Nepali).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(ne).freeze,
      label: "Nepali".freeze,
      "skos:notation" => %(ne).freeze,
      "skos:prefLabel" => %(Nepali).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :ng,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Ndonga).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(ng).freeze,
      label: "Ndonga".freeze,
      "skos:notation" => %(ng).freeze,
      "skos:prefLabel" => %(Ndonga).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :nl,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Dutch |  Flemish).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(nl).freeze,
      label: ["Dutch |  Flemish".freeze, "Dutch | Flemish".freeze],
      "skos:notation" => %(nl).freeze,
      "skos:prefLabel" => %(Dutch | Flemish).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :nn,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Norwegian Nynorsk |  Nynorsk, Norwegian).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(nn).freeze,
      label: ["Norwegian Nynorsk |  Nynorsk, Norwegian".freeze, "Norwegian Nynorsk | Nynorsk, Norwegian".freeze],
      "skos:notation" => %(nn).freeze,
      "skos:prefLabel" => %(Norwegian Nynorsk | Nynorsk, Norwegian).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :no,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Norwegian).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(no).freeze,
      label: "Norwegian".freeze,
      "skos:notation" => %(no).freeze,
      "skos:prefLabel" => %(Norwegian).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :nr,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Ndebele, South |  South Ndebele).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(nr).freeze,
      label: ["Ndebele, South |  South Ndebele".freeze, "Ndebele, South | South Ndebele".freeze],
      "skos:notation" => %(nr).freeze,
      "skos:prefLabel" => %(Ndebele, South | South Ndebele).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :nv,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Navajo |  Navaho).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(nv).freeze,
      label: ["Navajo |  Navaho".freeze, "Navajo | Navaho".freeze],
      "skos:notation" => %(nv).freeze,
      "skos:prefLabel" => %(Navajo | Navaho).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :ny,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Chichewa |  Chewa |  Nyanja).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(ny).freeze,
      label: ["Chichewa |  Chewa |  Nyanja".freeze, "Chichewa | Chewa | Nyanja".freeze],
      "skos:notation" => %(ny).freeze,
      "skos:prefLabel" => %(Chichewa | Chewa | Nyanja).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :oc,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Occitan \(post 1500\)).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(oc).freeze,
      label: "Occitan (post 1500)".freeze,
      "skos:notation" => %(oc).freeze,
      "skos:prefLabel" => %(Occitan \(post 1500\)).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :oj,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Ojibwa).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(oj).freeze,
      label: "Ojibwa".freeze,
      "skos:notation" => %(oj).freeze,
      "skos:prefLabel" => %(Ojibwa).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :om,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Oromo).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(om).freeze,
      label: "Oromo".freeze,
      "skos:notation" => %(om).freeze,
      "skos:prefLabel" => %(Oromo).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :or,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Oriya).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(or).freeze,
      label: "Oriya".freeze,
      "skos:notation" => %(or).freeze,
      "skos:prefLabel" => %(Oriya).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :os,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Ossetian |  Ossetic).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(os).freeze,
      label: ["Ossetian |  Ossetic".freeze, "Ossetian | Ossetic".freeze],
      "skos:notation" => %(os).freeze,
      "skos:prefLabel" => %(Ossetian | Ossetic).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :pa,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Panjabi |  Punjabi).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(pa).freeze,
      label: ["Panjabi |  Punjabi".freeze, "Panjabi | Punjabi".freeze],
      "skos:notation" => %(pa).freeze,
      "skos:prefLabel" => %(Panjabi | Punjabi).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :pi,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Pali).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(pi).freeze,
      label: "Pali".freeze,
      "skos:notation" => %(pi).freeze,
      "skos:prefLabel" => %(Pali).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :pl,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Polish).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(pl).freeze,
      label: "Polish".freeze,
      "skos:notation" => %(pl).freeze,
      "skos:prefLabel" => %(Polish).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :ps,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Pushto |  Pashto).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(ps).freeze,
      label: ["Pushto |  Pashto".freeze, "Pushto | Pashto".freeze],
      "skos:notation" => %(ps).freeze,
      "skos:prefLabel" => %(Pushto | Pashto).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :pt,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Portuguese).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(pt).freeze,
      label: "Portuguese".freeze,
      "skos:notation" => %(pt).freeze,
      "skos:prefLabel" => %(Portuguese).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :qu,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Quechua).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(qu).freeze,
      label: "Quechua".freeze,
      "skos:notation" => %(qu).freeze,
      "skos:prefLabel" => %(Quechua).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :rm,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Romansh).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(rm).freeze,
      label: "Romansh".freeze,
      "skos:notation" => %(rm).freeze,
      "skos:prefLabel" => %(Romansh).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :rn,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Rundi).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(rn).freeze,
      label: "Rundi".freeze,
      "skos:notation" => %(rn).freeze,
      "skos:prefLabel" => %(Rundi).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :ro,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Romanian |  Moldavian |  Moldovan).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(ro).freeze,
      label: ["Romanian |  Moldavian |  Moldovan".freeze, "Romanian | Moldavian | Moldovan".freeze],
      "skos:notation" => %(ro).freeze,
      "skos:prefLabel" => %(Romanian | Moldavian | Moldovan).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :ru,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Russian).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(ru).freeze,
      label: "Russian".freeze,
      "skos:notation" => %(ru).freeze,
      "skos:prefLabel" => %(Russian).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :rw,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Kinyarwanda).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(rw).freeze,
      label: "Kinyarwanda".freeze,
      "skos:notation" => %(rw).freeze,
      "skos:prefLabel" => %(Kinyarwanda).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :sa,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Sanskrit).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(sa).freeze,
      label: "Sanskrit".freeze,
      "skos:notation" => %(sa).freeze,
      "skos:prefLabel" => %(Sanskrit).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :sc,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Sardinian).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(sc).freeze,
      label: "Sardinian".freeze,
      "skos:notation" => %(sc).freeze,
      "skos:prefLabel" => %(Sardinian).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :sd,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Sindhi).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(sd).freeze,
      label: "Sindhi".freeze,
      "skos:notation" => %(sd).freeze,
      "skos:prefLabel" => %(Sindhi).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :se,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Northern Sami).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(se).freeze,
      label: "Northern Sami".freeze,
      "skos:notation" => %(se).freeze,
      "skos:prefLabel" => %(Northern Sami).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :sg,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Sango).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(sg).freeze,
      label: "Sango".freeze,
      "skos:notation" => %(sg).freeze,
      "skos:prefLabel" => %(Sango).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :si,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Sinhala |  Sinhalese).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(si).freeze,
      label: ["Sinhala |  Sinhalese".freeze, "Sinhala | Sinhalese".freeze],
      "skos:notation" => %(si).freeze,
      "skos:prefLabel" => %(Sinhala | Sinhalese).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :sk,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Slovak).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(sk).freeze,
      label: "Slovak".freeze,
      "skos:notation" => %(sk).freeze,
      "skos:prefLabel" => %(Slovak).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :sl,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Slovenian).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(sl).freeze,
      label: "Slovenian".freeze,
      "skos:notation" => %(sl).freeze,
      "skos:prefLabel" => %(Slovenian).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :sm,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Samoan).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(sm).freeze,
      label: "Samoan".freeze,
      "skos:notation" => %(sm).freeze,
      "skos:prefLabel" => %(Samoan).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :sn,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Shona).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(sn).freeze,
      label: "Shona".freeze,
      "skos:notation" => %(sn).freeze,
      "skos:prefLabel" => %(Shona).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :so,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Somali).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(so).freeze,
      label: "Somali".freeze,
      "skos:notation" => %(so).freeze,
      "skos:prefLabel" => %(Somali).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :sq,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Albanian).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(sq).freeze,
      label: "Albanian".freeze,
      "skos:notation" => %(sq).freeze,
      "skos:prefLabel" => %(Albanian).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :sr,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Serbian).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(sr).freeze,
      label: "Serbian".freeze,
      "skos:notation" => %(sr).freeze,
      "skos:prefLabel" => %(Serbian).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :ss,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Swati).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(ss).freeze,
      label: "Swati".freeze,
      "skos:notation" => %(ss).freeze,
      "skos:prefLabel" => %(Swati).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :st,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Sotho, Southern).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(st).freeze,
      label: "Sotho, Southern".freeze,
      "skos:notation" => %(st).freeze,
      "skos:prefLabel" => %(Sotho, Southern).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :su,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Sundanese).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(su).freeze,
      label: "Sundanese".freeze,
      "skos:notation" => %(su).freeze,
      "skos:prefLabel" => %(Sundanese).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :sv,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Swedish).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(sv).freeze,
      label: "Swedish".freeze,
      "skos:notation" => %(sv).freeze,
      "skos:prefLabel" => %(Swedish).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :sw,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Swahili).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(sw).freeze,
      label: "Swahili".freeze,
      "skos:notation" => %(sw).freeze,
      "skos:prefLabel" => %(Swahili).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :ta,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Tamil).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(ta).freeze,
      label: "Tamil".freeze,
      "skos:notation" => %(ta).freeze,
      "skos:prefLabel" => %(Tamil).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :te,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Telugu).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(te).freeze,
      label: "Telugu".freeze,
      "skos:notation" => %(te).freeze,
      "skos:prefLabel" => %(Telugu).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :tg,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Tajik).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(tg).freeze,
      label: "Tajik".freeze,
      "skos:notation" => %(tg).freeze,
      "skos:prefLabel" => %(Tajik).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :th,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Thai).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(th).freeze,
      label: "Thai".freeze,
      "skos:notation" => %(th).freeze,
      "skos:prefLabel" => %(Thai).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :ti,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Tigrinya).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(ti).freeze,
      label: "Tigrinya".freeze,
      "skos:notation" => %(ti).freeze,
      "skos:prefLabel" => %(Tigrinya).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :tk,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Turkmen).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(tk).freeze,
      label: "Turkmen".freeze,
      "skos:notation" => %(tk).freeze,
      "skos:prefLabel" => %(Turkmen).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :tl,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Tagalog).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(tl).freeze,
      label: "Tagalog".freeze,
      "skos:notation" => %(tl).freeze,
      "skos:prefLabel" => %(Tagalog).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :tn,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Tswana).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(tn).freeze,
      label: "Tswana".freeze,
      "skos:notation" => %(tn).freeze,
      "skos:prefLabel" => %(Tswana).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :to,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Tonga \(Tonga Islands\)).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(to).freeze,
      label: "Tonga (Tonga Islands)".freeze,
      "skos:notation" => %(to).freeze,
      "skos:prefLabel" => %(Tonga \(Tonga Islands\)).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :tr,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Turkish).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(tr).freeze,
      label: "Turkish".freeze,
      "skos:notation" => %(tr).freeze,
      "skos:prefLabel" => %(Turkish).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :ts,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Tsonga).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(ts).freeze,
      label: "Tsonga".freeze,
      "skos:notation" => %(ts).freeze,
      "skos:prefLabel" => %(Tsonga).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :tt,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Tatar).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(tt).freeze,
      label: "Tatar".freeze,
      "skos:notation" => %(tt).freeze,
      "skos:prefLabel" => %(Tatar).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :tw,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Twi).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(tw).freeze,
      label: "Twi".freeze,
      "skos:notation" => %(tw).freeze,
      "skos:prefLabel" => %(Twi).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :ty,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Tahitian).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(ty).freeze,
      label: "Tahitian".freeze,
      "skos:notation" => %(ty).freeze,
      "skos:prefLabel" => %(Tahitian).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :ug,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Uighur |  Uyghur).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(ug).freeze,
      label: ["Uighur |  Uyghur".freeze, "Uighur | Uyghur".freeze],
      "skos:notation" => %(ug).freeze,
      "skos:prefLabel" => %(Uighur | Uyghur).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :uk,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Ukrainian).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(uk).freeze,
      label: "Ukrainian".freeze,
      "skos:notation" => %(uk).freeze,
      "skos:prefLabel" => %(Ukrainian).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :ur,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Urdu).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(ur).freeze,
      label: "Urdu".freeze,
      "skos:notation" => %(ur).freeze,
      "skos:prefLabel" => %(Urdu).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :uz,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Uzbek).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(uz).freeze,
      label: "Uzbek".freeze,
      "skos:notation" => %(uz).freeze,
      "skos:prefLabel" => %(Uzbek).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :ve,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Venda).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(ve).freeze,
      label: "Venda".freeze,
      "skos:notation" => %(ve).freeze,
      "skos:prefLabel" => %(Venda).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :vi,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Vietnamese).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(vi).freeze,
      label: "Vietnamese".freeze,
      "skos:notation" => %(vi).freeze,
      "skos:prefLabel" => %(Vietnamese).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :vo,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Volapük).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(vo).freeze,
      label: "Volapük".freeze,
      "skos:notation" => %(vo).freeze,
      "skos:prefLabel" => %(Volapük).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :wa,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Walloon).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(wa).freeze,
      label: "Walloon".freeze,
      "skos:notation" => %(wa).freeze,
      "skos:prefLabel" => %(Walloon).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :wo,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Wolof).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(wo).freeze,
      label: "Wolof".freeze,
      "skos:notation" => %(wo).freeze,
      "skos:prefLabel" => %(Wolof).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :xh,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Xhosa).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(xh).freeze,
      label: "Xhosa".freeze,
      "skos:notation" => %(xh).freeze,
      "skos:prefLabel" => %(Xhosa).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :yi,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Yiddish).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(yi).freeze,
      label: "Yiddish".freeze,
      "skos:notation" => %(yi).freeze,
      "skos:prefLabel" => %(Yiddish).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :yo,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Yoruba).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(yo).freeze,
      label: "Yoruba".freeze,
      "skos:notation" => %(yo).freeze,
      "skos:prefLabel" => %(Yoruba).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :za,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Zhuang |  Chuang).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(za).freeze,
      label: ["Zhuang |  Chuang".freeze, "Zhuang | Chuang".freeze],
      "skos:notation" => %(za).freeze,
      "skos:prefLabel" => %(Zhuang | Chuang).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :zh,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Chinese).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(zh).freeze,
      label: "Chinese".freeze,
      "skos:notation" => %(zh).freeze,
      "skos:prefLabel" => %(Chinese).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
    term :zu,
      "http://www.loc.gov/mads/rdf/v1#authoritativeLabel" => %(Zulu).freeze,
      "http://www.loc.gov/mads/rdf/v1#code" => %(zu).freeze,
      label: "Zulu".freeze,
      "skos:notation" => %(zu).freeze,
      "skos:prefLabel" => %(Zulu).freeze,
      type: ["http://www.loc.gov/mads/rdf/v1#Language".freeze, "http://www.loc.gov/mads/rdf/v1#Authority".freeze, "http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language".freeze, "skos:Concept".freeze]
  end
end
